name: lint_format
on: [push, pull_request]

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      OS: ubuntu-latest
      PYTHON: "3.10"

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: "2"

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install black flake8

      - name: Lint code
        run: flake8 .

      - name: Autoformat code
        run: black .

      - name: Generate Report
        run: |
          pip install coverage
          coverage run -m unittest

      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v2
